### ISSUE TITLE
Неясность с относительной высотой

### ISSUE THREAD

**Issue by ushakova-ea** [unngrouponce/unn_grouponce#58]
Последовательность действий: Создать объект класса Image с помощью конструктора Image(Bitmap image, double tall = 0, bool copySourceToOutput = false). Исходная картинка sample_10.png
Ожидаемый результат: Параметр tall=10 (относительная высота, на котором сделано изображение)
Действительный результат: Параметр tall=0 

Если так должно быть, то объяснить почему

**Comment by arechesk** [comment]
А можно код увидеть, как создавала объект?

**Comment by arechesk** [comment]
tall нужно самому явно указывать

**Comment by ushakova-ea** [comment]
у нас же относительная высота должна считываться из файла
А если у нас будет 100 изображений с разными высотами, то как тогда? все ручками делать?

**Comment by ushakova-ea** [comment]
да я явно задаю этот параметр, он равен 0

**Comment by arechesk** [comment]
**Да, ты права здесь tall лучше удалить.**
